# Generated by Django 3.2 on 2021-04-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_rename_package_file_aippackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='uploads/images'),
        ),
    ]
