# Generated by Django 3.2 on 2021-04-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_alter_file_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='aippackage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='filetype',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
